### ISSUE TITLE
Enabling this extension disables syntax highlighting in .md files

### ISSUE THREAD

**Issue by jwulf** [fivethree-team/vscode-hugo-snippets#1]
Love the snippets, but when I enable this extension, I lose all syntax highlighting in my .md file!

**Comment by marcjulian** [comment]
Yes I have noticed the same issue. I wasn't able to find a fix. I let you know when its fixed!

**Comment by marcjulian** [comment]
I published a new version `0.1.2` the syntax highlighting should work again. I got it working in `md` files with typing `h-` and using code completion shortcut to see the snippet options. The snippets are currently not shown automatically for `md` files.
