### ISSUE TITLE
Extension doesn't seem to be working/enabled after install

### ISSUE THREAD

**Issue by tansawit** [fivethree-team/vscode-hugo-snippets#3]
I've tried to install the extension and use it on one of my Markdown files inside my Hugo site directory. However, typing 'h-' doesn't bring up any prompts and typing some of the examples does nothing either. Is there something I must do/enable before using the extension?

VS Code: Version: 1.38.1
Extensions Enabled: [Markdown All in One, Markdown Preview Enhanced, Markdown Lint, Hugo Helper, Hugo Snippets, Hugo Language and Syntax Support]

**Comment by marcjulian** [comment]
You can trigger suggest the snippets with `^Space` in Markdown file https://code.visualstudio.com/docs/languages/markdown#_snippets-for-markdown

**Comment by marcjulian** [comment]
I have added this to the [readme](https://github.com/fivethree-team/vscode-hugo-snippets#trigger-markdown)
