### ISSUE TITLE
 Publish to Open VSX registry

### ISSUE THREAD

**Issue by py-crash** [fivethree-team/vscode-hugo-snippets#4]
I've been using your extension in [VSCodium](https://vscodium.com/), the open source binary version on Visual Studio Code, and now it integrated the [Open VSX registry](https://open-vsx.org) as an Open Source alternative to the Microsoft Marketplace (since the license doesn't allow to use it in other projects).
I would love to see your extension in the new marketplace.

**Comment by marcjulian** [comment]
@py-crash thanks for sharing Open VSX registry. I have published Hugo Snippets https://open-vsx.org/extension/fivethree/vscode-hugo-snippets

If you like the extension feel free to add PR's with new feature 😄

**Comment by py-crash** [comment]
Great! Thank you
